### ISSUE TITLE
Issue when Atom detects C++14

### ISSUE THREAD

**Issue by Adobe-Android** [tomlau10/gcc-make-run#1]
I haven't given a look at the code, but it seems like you have hard file names set for .c, .cpp, and makefiles. Unfortunately, when Atom auto-detects C++14 compliant code, your amazing plugin breaks (I'm being serious here, I really do love it). If you could fix this, I'd appreciate it a lot (This might also occur for other standards too, but I haven't looked into it). Thanks.
Edit: Took a look at it and forked it. I'll send at least one fix. Also, this seems to occur due to the "Language Cpp14" plugin.

**Comment by tomlau10** [comment]
Thanks for giving a try on my plugin and having time to make pull request ;)
Pull Request #2 @Adobe-Android

**Comment by Adobe-Android** [comment]
No problem. I was looking for some cool C++ plugins and really liked yours.
I ran into an unfortunate compatibility with another one I was trying to
use. I really appreciate you accepting it. I'm actually not familiar with
CoffeeScript, but it holds the same general programming ideas and was
really easy to understand. Keep up the good work.

**Comment by tomlau10** [comment]
Oh just now I forgot to test it with the language-cpp14 plugin, and now I found that actually one more line needs to be added. I will push a fix soon.

**Comment by tomlau10** [comment]
Fixed with commit 9238350184c5ebbc1dd5972307ebd92aa4d77989

**Comment by Adobe-Android** [comment]
Okay cool. I'll test it sometime later and I look forward to seeing the
changes.
