### ISSUE TITLE
Two terminal windows instead of one.

### ISSUE THREAD

**Issue by yougotwill** [tomlau10/gcc-make-run#10]
Great package. Just one problem when I run it, two terminal windows are opened instead of one and when it closes the terminal it only closes one of the windows. (On Mac OSX).

Keep up the good work 👍

**Comment by MethylatorX** [comment]
Here is a work around it(I assume you're using Apple's Terminal.app). Preferences > Profiles > Shell. From "When the shell exits" chose "Close the window".

Also we would like an option to add/use a custom terminal emulator (for instance xterm/gnome-terminal/terminator...etc).

**Comment by yougotwill** [comment]
Thanks :) Yeah that would be great.

**Comment by tomlau10** [comment]
@MethylatorX 
I think the difficulties for `custom terminal emulator` lie on `how to invoke the compiled program in different terminal`.

To achieve the current behavior (`press to exit`, `passing arguments`, etc)
It is not as easy as just `xterm ./a.out`. (you may take a look at the [current command](https://github.com/tomlau10/gcc-make-run/blob/master/lib/gcc-make-run.coffee#L233))

Moreover, any options need to care about cross platform behavior.

Anyway thanks for your suggestions and I may think about it :smiley:
