### ISSUE TITLE
Make Run & Compile Run - Double Window

### ISSUE THREAD

**Issue by Dreded** [tomlau10/gcc-make-run#12]
Whenever I run either command it opens two command windows... no other method of running the file results in this even with other plugins

and right after I submitted this I ran the plugin again and got 3 windows and now 4.... and now 5...

Ok Figured it out everytime I uninstall/disable and re-enable plugin I get an additional window popping up

fixed it by uninstalling then closing atom then re-installing

**Comment by dlwalter** [comment]
Same issue.  Uninstalling and Reinstalling results in multiple calls to make when 'make run' is selected from the contex menu.

**Comment by tomlau10** [comment]
sorry for a bit late 😅 

---
found the cause:
when deactivate the package, did not dispose the subscribed editor commands
thus when reactivating, it registered the editor commands again ...

will fix it when i have time
