### ISSUE TITLE
Compile error because of surrounding ""

### ISSUE THREAD

**Issue by ChaosHelme** [tomlau10/gcc-make-run#15]
Hi,
I just tried out your nice package for Atom. I set up my tdm-gcc and followed your instructions for Windows. Unfortunetly, I'm getting an error telling me that the commands ""gcc"" or ""mingw32-make"" could not be found. It's weird that the error shows the commands with extra surrounding "". Did I do something wrong?

![settings](https://cloud.githubusercontent.com/assets/16524486/24270815/effa5614-1016-11e7-8943-3bbabe6983ee.JPG)
![path](https://cloud.githubusercontent.com/assets/16524486/24270820/f2478c52-1016-11e7-9084-2ce72eb09593.JPG)
![error](https://cloud.githubusercontent.com/assets/16524486/24270822/f42996aa-1016-11e7-82d2-6fc28639c9b9.JPG)

**Comment by tomlau10** [comment]
thanks for using, but sorry i cant reproduce this problem :thinking: 
even if i change the gcc compiler in the settings to `""gcc""`, it works

![image](https://cloud.githubusercontent.com/assets/16996876/24276285/7c89586a-1070-11e7-9480-bc3ead5acca3.png)

---
after setting the `PATH` environment variable, did you try restarting `atom` || `explorer` || `computer` ?
sometimes the `$PATH` may require a restart to work
also when you open a `cmd` console, can you run `gcc` there directly?

**Comment by ChaosHelme** [comment]
Alright, so I feel a little dump now, but yeah finally after several restarts in works just fine. Seems like a problem / bug with the $PATH?!

Thanks for your help, I close this case ;)
