### ISSUE TITLE
Can't change to other than Xterm

### ISSUE THREAD

**Issue by luna-niemitalo** [tomlau10/gcc-make-run#18]
Can not change to use my normal terminal program.

**Comment by tomlau10** [comment]
i am a windows user and currently this package has a limited support for cross platform
as `compile run (c / c++ file)` or `make run (makefile)` may require a whole different set of commands
so it seems no easy way 🤔

**Comment by luna-niemitalo** [comment]
Submitted pull request fixing the issue.
Closing issue.
