### ISSUE TITLE
C++ compiler not compiling iostream

### ISSUE THREAD

**Issue by PedroSilva8** [tomlau10/gcc-make-run#21]
For some reason when using  gcc-make-run to compile c++ it doesn't compile `#include <iostream>` but when compiling the same code manually with mingw

**Comment by tomlau10** [comment]
this plugin used `editor's grammar` to detect which compiler (`gcc` or `g++`) to use
seems that atom treated your file as a `c` file
then it used the `gcc` compiler and cause errors like `undefined reference to `std::ios_base::Init::~Init()`

---
1. you need to change the editor's grammar (default hotkey `ctrl` + `shift` + `L`) to c++
2. or add a library flag `-lstdc++` in build option so you can still use `gcc` compiler

**Comment by PedroSilva8** [comment]
@tomlau10 it isn't giving me any error like this `undefined reference tostd::ios_base::Init::~Init()`  and grammar is treated like c++

**Comment by tomlau10** [comment]
can you screen capture and paste the error && file content here? 🤔
