### ISSUE TITLE
Custom terminal string brakes atom ability to load main config.cson

### ISSUE THREAD

**Issue by luna-niemitalo** [tomlau10/gcc-make-run#23]
problem appears after commit:
https://github.com/tomlau10/gcc-make-run/commit/12b4cf64878b0713a995275db6924f6512bbf292 

terminal string i am using is "konsole -T #{title} -e"
Error from atom
> Failed to load config.cson
> Syntax error on line 8, column 29: Unexpected token i in JSON at position 1

From what i think happens is that default terminal string is not saved in config.cson so error does not occur, but if user edits terminal string it gets saved to config.cson and atom does not like some character in that config line so it refuces to load config.

EDIT: my config looks like this 

> "*":
>   core:
>     telemetryConsent: "limited"
>   "exception-reporting":
>     userId: "*userid*"
>   "gcc-make-run":
>     ldlibs: "-lssl -lcurl -lpthread -lsfml-graphics -lsfml-window -lsfml-system"
>     terminal: "konsole -T #{title} -e"

**Comment by tomlau10** [comment]
this is my fault ...
shouldn't use `#{abc}` in the config string as variable replacement in coffee script
as this is used for the language's own variable replacement ...

---
i will change to `$abc` instead
before the fix, you may need to manually delete the `terminal` key in config.cson
sorry for that
