### ISSUE TITLE
The C file build successfully but no command  windows appear

### ISSUE THREAD

**Issue by fengkx** [tomlau10/gcc-make-run#24]
I am using Ubuntu.Previously, I use this package successfully. But now it doesn't appear a window. How can I fix this. I just switch my shell from bash to zsh. Is it the fault

**Comment by tomlau10** [comment]
can you screen capture the package's config page?
did you customized the `terminal start command`?
would resetting this config to default be helpful?

**Comment by fengkx** [comment]
Sorry, I am just a beginer. I think I didn't customized the `terminal star com` after I google it. and here is the config page: http://oretxrabb.bkt.clouddn.com/Screenshot%20from%202017-09-09%2023-35-37.png. It is all default config. This problem appear when I switch my shell from bash to zsh
