### ISSUE TITLE
No Auto save before compilimg

### ISSUE THREAD

**Issue by TheSharpOwl** [tomlau10/gcc-make-run#28]
Can you please add a choice to save before compiling,because if I forget to save the code before compiling it compiles the last one saved.

**Comment by tomlau10** [comment]
this package has auto save before compiling
but it broke after atom 1.19 due to the `save()` becoming async #19 
will fix soon

**Comment by tomlau10** [comment]
should be fixed in 8f56715

**Comment by Maickii** [comment]
Can you please change it so that it saves all files rather than just the current selected pane? I work compiling multiple files. I think doing something with `saveAll()` should do the trick. In the meantime I am going to install an auto save all package.
