### ISSUE TITLE
Customized key bindings instead of F6

### ISSUE THREAD

**Issue by hpdipto** [tomlau10/gcc-make-run#42]
How can I configure my own key bindings for running the program instead of default F6?

**Comment by glevy03** [comment]
Hello, How are you?
You need to go to Settings --> Packages --> gcc-make-run (don't open it just make sure you can see it) --> Settings (of the gcc-make-run) --> View Code. In the folder "Keymaps", enter the file "gcc-make-run.cson" - look for the letters "f6" - change it to whatever you want (if you want combined keys, put a dash (-) between each key, like this: ctrl-alt-g). Now you need to save this file, and reset Atom.
I hope I was helpful :)
Cheers, glevy03
