### ISSUE TITLE
gcc: error: unrecognized command line option '-f'

### ISSUE THREAD

**Issue by 771240158** [tomlau10/gcc-make-run#46]
I can Run it with normal compilation, but I right-click on my project Make Run and he shows where the error -f came from?
![so](https://user-images.githubusercontent.com/35726247/41585372-72545a86-73dc-11e8-8fa7-9bc3c042779c.png)

**Comment by tomlau10** [comment]
I know it's a bit late.
The `Make Run` feature is to use the `make` utility to run `Makefile`. From the screenshot, you incorrectly set it to `gcc` as it is the compiler not the `make` utility. You should have left it empty or point to the path of `make.exe`.

The underlying command when running makefile is `make -f <Makefile>`.
