### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by zXwilt** [tomlau10/gcc-make-run#47]
When I used gcc-make-run to compile a project, the compiler report this error:
![image](https://user-images.githubusercontent.com/40575046/41863585-2652d7bc-789f-11e8-9ded-5b8a2fa5b833.png)

How can I link multiple files with gcc make run?

**Comment by tomlau10** [comment]
It's a bit late.

With **Compile Run**, the **directory of the file you trigger** will be the **working directory**. In this way when you write `#include "header.h"` in your `main.cpp`, and trigger **Compile Run** on the `main.cpp`, the compiler will expect `header.h` to be in the same directory as `main.cpp`.

So in case your folder structure is:
```
./main.cpp
./inc/header.h
```
then you have to write `#include "inc/header.h"` in the `main.cpp`.

---
Another option is to use the `-I` flag of the compiler to specify the directory of headers to be searched for.
In the above example, we can use `-Iinc` to let the compiler search headers in `inc` directory, then we can simply write `"header.h"` in `main.cpp`.
