### ISSUE TITLE
Add option for file extension

### ISSUE THREAD

**Issue by adiultra** [tomlau10/gcc-make-run#5]
When quickly comipiling and running I want to have the feature to specify the `.out` or similar extension to the output file rather than the default same name of source file.

The only reason for this is that the git would then ignore these executables.

Thanks anyways for a better c++/g++ integration with atom.

**Comment by tomlau10** [comment]
Thanks for your suggestion!
I am busying with my school projects this few weeks, would add this feature afterwards.
