### ISSUE TITLE
How can I use it with Konsole?

### ISSUE THREAD

**Issue by hytousuce** [tomlau10/gcc-make-run#53]
I have tried to use the terminal start command `konsole -T $title --hold -e`. 
To a certain extent, it's going well. But I can't turn the Konsole off by pressing any key. I can't stand it however.
Is there any solution?

**Comment by SupremeManggo** [comment]
Hi, @kongjune 

I am on Solus OS and konsole is my terminal too.

Try this on Terminal Start Command on GCC make run settings

konsole -e bash -c 

works for me

**Comment by r0ngk** [comment]
Try this: konsole -T $title -e bash -c
