### ISSUE TITLE
 how to run Makefile without tab open?

### ISSUE THREAD

**Issue by sergerold** [tomlau10/gcc-make-run#57]
Hi

I’m using gcc-make-run to compile using a Makefile. However, it seems that you can only use gcc-make-run when the Makefile is actively open. Instead, I’d like to run the Makefile without it being open - is there no way of specifying this.

I did look on the gcc-make-run page but it wasn’t very clear so I’m asking here.

Thanks

**Comment by tomlau10** [comment]
It's a bit late, but another way to run `Makefile` is **right click it at tree view**, then choose make run.
This is the [Execute Makefile from Tree View](https://github.com/tomlau10/gcc-make-run#features) feature.
