### ISSUE TITLE
I can't use STL in my code

### ISSUE THREAD

**Issue by Chen-ClearSkies** [tomlau10/gcc-make-run#59]
If I use STL in my code,it will not input anything and stop at once.

I'm a Chinese middle school student ,so my English is not very good.Please forgive me.

**Comment by tomlau10** [comment]
It's a bit late, but I just tested a **C++ STL** sample code from [this site](https://www.runoob.com/cplusplus/cpp-stl-tutorial.html) in **[Pulsar Editor](https://pulsar-edit.dev/)** (a fork of Atom Editor) with this plugin without any issue. 😕
