### ISSUE TITLE
Run Arguments

### ISSUE THREAD

**Issue by Weslysilva** [tomlau10/gcc-make-run#6]
Mr's. 

After new update;
the use of "Run Arguments" Stopped working in "toggle run options" for set arguments.

Att,
Wesly Silva.
ENG Software.

**Comment by tomlau10** [comment]
opps
sorry that i replaced the `input` element with `atom-text-editor` element in the last update but forgot to change the getter setter of the element text content in run option view

i will fix it as soon as possible

**Comment by Weslysilva** [comment]
Thank you Mr. Lau.

his solution was quick and efficient.

sorry not to have given so fast feedback when your :)

2016-05-22 13:02 GMT-03:00 Lau Cheuk Yin notifications@github.com:
